ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Chlorine Canister"
ENT.Category = "W-City: Другое"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.totalparticles = 60
ENT.Model = "models/props_junk/propanecanister001as.mdl"
ENT.IconOverride = "vgui/wep_jack_hmcd_chlorine"